### ISSUE TITLE
Spreadsheet missing

### ISSUE THREAD

**Issue by philbywalsh** [avi-rn/expected-blocks#1]
Great project!

I see that on this line below there's a reference to an excel spreadsheet

`temp_xga = pd.read_excel('prem2223.xlsx')`

When I try to run this line I get the error below

`FileNotFoundError: [Errno 2] No such file or directory: 'prem2223.xlsx'`

Because this file doesn't exist. It's not present in the project in Git and doesn't seem to be generated by any of the lines of code above  this line of code.

Where can I source this spreadsheet?

**Comment by avi-rn** [comment]
Hi! Thanks for bringing this to my attention. I have added the spreadsheet to the repo and attached for your convenience. Let me know if there are any other issues!
[prem2223.xlsx](https://github.com/avi-rn/expected-blocks/files/11154562/prem2223.xlsx)
